name: Build EXE and DMG

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-windows:
    name: Windows - Build EXE
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Download JavaFX SDK
        run: |
          mkdir javafx
          curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/21.0.8/openjfx-21.0.8_windows-x64_bin-sdk.zip
          tar -xf javafx.zip -C javafx --strip-components=1

      - name: Build with Maven
        run: mvn clean package

      - name: Clean duplicate JARs
        shell: cmd
        run: del /F /Q app\target\lib\okio-jvm-3.6.0.jar

      - name: Verify build artifacts
        shell: cmd
        run: |
          echo "Checking target directory structure:"
          dir /s app\target
          echo "Checking JavaFX directory structure:"
          dir /s javafx
          echo "Main JAR file size:"
          dir app\target\app-1.0-SNAPSHOT.jar

      - name: Package EXE with jpackage
        shell: cmd
        run: |
          jpackage --name NovaScrape ^
          --type exe ^
          --input app\target ^
          --main-jar app-1.0-SNAPSHOT.jar ^
          --main-class fr.nova.novascrape.Main ^
          --runtime-image "%JAVA_HOME%" ^
          --dest target\installer ^
          --win-dir-chooser ^
          --win-menu ^
          --win-shortcut ^
          --verbose

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: NovaScrape-Windows
          path: target\installer\NovaScrape-*.exe

  build-macos:
    name: macOS - Build DMG
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Download JavaFX SDK
        run: |
          mkdir javafx
          curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/21.0.8/openjfx-21.0.8_osx-aarch64_bin-sdk.zip
          unzip javafx.zip -d javafx
          ls -la javafx

      - name: Build with Maven
        run: mvn clean package

      - name: Clean duplicate JARs
        run: rm -f app/target/lib/okio-jvm-3.6.0.jar

      - name: Verify build artifacts
        run: |
          echo "Checking target directory structure:"
          ls -R app/target
          echo "Checking JavaFX directory structure:"
          ls -R javafx
          echo "Main JAR file size:"
          ls -lh app/target/app-1.0-SNAPSHOT.jar

      - name: Package DMG with jpackage
        run: |
          jpackage --name NovaScrape \
            --type dmg \
            --input app/target \
            --main-jar app-1.0-SNAPSHOT.jar \
            --main-class fr.nova.novascrape.Main \
            --runtime-image "$JAVA_HOME" \
            --dest target/installer \
            --mac-package-identifier fr.nova.novascrape \
            --mac-package-name NovaScrape \
            --verbose

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: NovaScrape-macOS
          path: target/installer/NovaScrape-*.dmg

  release:
    name: Create GitHub Release
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: NovaScrape-Windows
          path: dist/windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: NovaScrape-macOS
          path: dist/macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_number }}
          files: |
            dist/windows/NovaScrape-*.exe
            dist/macos/NovaScrape-*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
